/**
 * Guard: the four-section writeup contract.
 * Spec: docs/superpowers/specs/2026-08-15-project-pages-design.md
 *
 * Every project record is held to RULES. Two escape maps, and they are NOT
 * the same thing:
 *
 *   ALLOWED  — permanent, sanctioned exceptions, each with its reason.
 *   BASELINE — temporary debt: records the rewrite has not reached yet.
 *
 * BASELINE only ever shrinks. Never add a slug; never add a rule to a slug.
 * Fill a project and delete its entry in the SAME commit — the stale test
 * fails otherwise, which is what stops this becoming a permission slip.
 *
 * Endgame: when BASELINE is empty, delete the constant, its filter, and
 * the stale test in one commit. The rules become absolute.
 */
import { describe, expect, it } from "vitest";
import { projectDetails } from "@/content/projects";
import type { ProjectDetail } from "@/content/types";

type Rule = {
  id: string;
  why: string;
  /** Returns a failure message, or null when the record satisfies the rule. */
  check: (d: ProjectDetail) => string | null;
};

const HEADINGS = ["THE PROBLEM", "WHAT IT DOES", "WHAT I BUILT", "WHERE IT BROKE"];
const CORE_FACTS = ["ROLE", "STACK", "STATUS"];

const RULES: Rule[] = [
  {
    id: "four-sections",
    why: "Every page answers why it exists, what it's like to have, how it works, and what went wrong.",
    check: (d) => {
      const got = d.sections.map((s) => s.heading);
      const missing = HEADINGS.filter((h) => !got.includes(h));
      return missing.length ? `missing section(s): ${missing.join(", ")}` : null;
    },
  },
  {
    id: "heading-order",
    why: "Problem, then payoff, then mechanism, then failure — a reader loses the thread in any other order.",
    check: (d) => {
      const idx = HEADINGS.map((h) => d.sections.findIndex((s) => s.heading === h)).filter((i) => i >= 0);
      const sorted = [...idx].sort((a, b) => a - b);
      return idx.join() === sorted.join() ? null : `contract sections are out of order`;
    },
  },
  {
    id: "five-facts",
    why: "The fact rail carries the page's right column; fewer than five rows leaves it visibly empty.",
    check: (d) => (d.facts.length >= 5 ? null : `${d.facts.length} fact rows, needs 5`),
  },
  {
    id: "core-fact-labels",
    why: "ROLE, STACK and STATUS are the three rows every project can answer honestly.",
    check: (d) => {
      const labels = d.facts.map((f) => f.label);
      const missing = CORE_FACTS.filter((l) => !labels.includes(l));
      return missing.length ? `missing fact row(s): ${missing.join(", ")}` : null;
    },
  },
  {
    id: "one-figure",
    why: "A page with no figure reads as a stub regardless of how good the copy is.",
    check: (d) => (d.figures.length >= 1 ? null : "no figure"),
  },
  {
    id: "premise-length",
    why: "The premise sits under the title at a 46ch measure; a one-liner leaves the header hollow.",
    check: (d) => (d.premise.length > 40 ? null : `premise is ${d.premise.length} chars, needs > 40`),
  },
];

/** Permanent, sanctioned exceptions. Each entry states what sanctions it. */
const ALLOWED: Record<string, string[]> = {};

/** Migration debt — generated by scripts/gen-writeup-baseline.ts. Shrinks only. */
const BASELINE: Record<string, string[]> = {
  "outdoor-telegram-agent": ["four-sections", "five-facts", "core-fact-labels", "one-figure", "premise-length"],
  "dynasty-analyzer": ["one-figure"],
  "tomkeefe-ai": ["one-figure"],
  "camera-agent": ["four-sections", "five-facts", "core-fact-labels", "one-figure", "premise-length"],
  "job-search": ["four-sections", "five-facts", "core-fact-labels", "one-figure", "premise-length"],
  "family-tree": ["four-sections", "five-facts", "core-fact-labels", "one-figure", "premise-length"],
  "code-coach": ["four-sections", "five-facts", "core-fact-labels", "one-figure", "premise-length"],
};

const failures = (d: ProjectDetail) =>
  RULES.filter((r) => !ALLOWED[d.slug]?.includes(r.id))
    .map((r) => ({ rule: r, msg: r.check(d) }))
    .filter((f) => f.msg !== null);

describe("writeup contract", () => {
  it("guard is armed", () => {
    // A refactor that empties or renames the export must not turn every rule
    // below into a no-op that passes on zero records.
    expect(projectDetails.length).toBeGreaterThanOrEqual(10);
  });

  for (const rule of RULES) {
    it(`${rule.id}: ${rule.why}`, () => {
      const hits = projectDetails
        .filter((d) => !ALLOWED[d.slug]?.includes(rule.id))
        .filter((d) => !BASELINE[d.slug]?.includes(rule.id))
        .map((d) => ({ slug: d.slug, msg: rule.check(d) }))
        .filter((h) => h.msg !== null);
      expect(hits.map((h) => `${h.slug} — ${h.msg}`)).toEqual([]);
    });
  }

  it("baseline is not stale", () => {
    const stale: string[] = [];
    for (const [slug, ids] of Object.entries(BASELINE)) {
      const d = projectDetails.find((p) => p.slug === slug);
      if (!d) {
        stale.push(`${slug} — no such project, delete the entry`);
        continue;
      }
      for (const id of ids) {
        const rule = RULES.find((r) => r.id === id);
        if (!rule) stale.push(`${slug} — unknown rule "${id}"`);
        else if (rule.check(d) === null) stale.push(`${slug} — "${id}" now passes, remove it from BASELINE`);
      }
    }
    expect(stale).toEqual([]);
  });

  it("every record reports its remaining debt accurately", () => {
    // Cross-check: a record's live failures must be a subset of its baseline.
    for (const d of projectDetails) {
      const live = failures(d).map((f) => f.rule.id);
      const listed = BASELINE[d.slug] ?? [];
      expect(live.filter((id) => !listed.includes(id))).toEqual([]);
    }
  });
});
